[2022-07-13 11:52:26,188] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: python_operator_dag_v7.get_age manual__2022-07-13T11:52:25.202568+00:00 [queued]>
[2022-07-13 11:52:26,206] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: python_operator_dag_v7.get_age manual__2022-07-13T11:52:25.202568+00:00 [queued]>
[2022-07-13 11:52:26,208] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 11:52:26,209] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-13 11:52:26,209] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 11:52:26,230] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_age> on 2022-07-13 11:52:25.202568+00:00
[2022-07-13 11:52:26,236] {standard_task_runner.py:52} INFO - Started process 11656 to run task
[2022-07-13 11:52:26,243] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'python_operator_dag_v7', 'get_age', 'manual__2022-07-13T11:52:25.202568+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag.py', '--cfg-path', '/tmp/tmp01e0k3tj', '--error-file', '/tmp/tmpx6csuxax']
[2022-07-13 11:52:26,247] {standard_task_runner.py:80} INFO - Job 53: Subtask get_age
[2022-07-13 11:52:26,373] {task_command.py:371} INFO - Running <TaskInstance: python_operator_dag_v7.get_age manual__2022-07-13T11:52:25.202568+00:00 [running]> on host 8e2218deeaf2
[2022-07-13 11:52:26,499] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=harshab
AIRFLOW_CTX_DAG_ID=python_operator_dag_v7
AIRFLOW_CTX_TASK_ID=get_age
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T11:52:25.202568+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-13T11:52:25.202568+00:00
[2022-07-13 11:52:26,502] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator_dag.py", line 25, in get_age
    ti.xcpm_push(key='age', value=25)
AttributeError: 'TaskInstance' object has no attribute 'xcpm_push'
[2022-07-13 11:52:26,525] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=python_operator_dag_v7, task_id=get_age, execution_date=20220713T115225, start_date=20220713T115226, end_date=20220713T115226
[2022-07-13 11:52:26,552] {standard_task_runner.py:97} ERROR - Failed to execute job 53 for task get_age ('TaskInstance' object has no attribute 'xcpm_push'; 11656)
[2022-07-13 11:52:26,575] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-13 11:52:26,641] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
